# Generated by Django 5.2.13 on 2026-04-25 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateTimeField()),
                ("promised_ship_by", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("skin_tone", models.CharField(max_length=50)),
                ("face_shape", models.CharField(max_length=50)),
                ("haircut", models.CharField(max_length=50)),
                ("hair_color", models.CharField(max_length=50)),
                ("eye_color", models.CharField(max_length=50)),
                ("outfit", models.CharField(max_length=50)),
                ("glasses", models.CharField(max_length=50)),
                ("status", models.CharField(default="received", max_length=50)),
                ("is_custom_build", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("target_date", models.DateField(unique=True)),
                ("target_orders", models.IntegerField(default=0)),
                ("target_assembled", models.IntegerField(default=0)),
                ("target_shipped", models.IntegerField(default=0)),
                ("actual_orders", models.IntegerField(default=0)),
                ("actual_assembled", models.IntegerField(default=0)),
                ("actual_shipped", models.IntegerField(default=0)),
                ("backlog_qty", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("defect_code", models.CharField(max_length=80, unique=True)),
                ("defect_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForecastParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("parameter_name", models.CharField(max_length=120, unique=True)),
                ("parameter_value", models.CharField(max_length=255)),
                ("parameter_type", models.CharField(default="string", max_length=50)),
                ("effective_start", models.DateField(blank=True, null=True)),
                ("effective_end", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("part_number", models.CharField(max_length=80, unique=True)),
                ("part_name", models.CharField(max_length=150)),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("arm", "Arm"),
                            ("leg", "Leg"),
                            ("hair", "Hair"),
                            ("eyes", "Eyes"),
                            ("outfit", "Outfit"),
                            ("glasses", "Glasses"),
                            ("torso", "Completed Soft Torso"),
                            ("packaging", "Packaging"),
                        ],
                        max_length=50,
                    ),
                ),
                ("skin_tone", models.CharField(blank=True, max_length=50, null=True)),
                ("face_shape", models.CharField(blank=True, max_length=50, null=True)),
                ("haircut", models.CharField(blank=True, max_length=50, null=True)),
                ("hair_color", models.CharField(blank=True, max_length=50, null=True)),
                ("eye_color", models.CharField(blank=True, max_length=50, null=True)),
                ("outfit", models.CharField(blank=True, max_length=50, null=True)),
                ("glasses", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unit_weight_grams",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("defect_opportunities", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("step_code", models.CharField(max_length=80, unique=True)),
                ("step_name", models.CharField(max_length=150)),
                ("sequence", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RootCauseCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("cause_code", models.CharField(max_length=80, unique=True)),
                ("cause_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("supplier_code", models.CharField(max_length=80, unique=True)),
                ("supplier_name", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=80)),
                ("iso_9001_current", models.BooleanField(default=False)),
                ("cpsia_current", models.BooleanField(default=False)),
                ("astm_f963_current", models.BooleanField(default=False)),
                ("oeko_tex_current", models.BooleanField(default=False)),
                ("foam_cert_current", models.BooleanField(default=False)),
                ("certification_expiry", models.DateField(blank=True, null=True)),
                (
                    "supplier_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TariffRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.CharField(max_length=80)),
                ("hts_code", models.CharField(blank=True, max_length=50, null=True)),
                ("tariff_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("effective_start", models.DateField()),
                ("effective_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("week_start", models.DateField(unique=True)),
                ("week_end", models.DateField()),
                ("target_orders", models.IntegerField(default=0)),
                ("target_assembled", models.IntegerField(default=0)),
                ("target_shipped", models.IntegerField(default=0)),
                ("actual_orders", models.IntegerField(default=0)),
                ("actual_assembled", models.IntegerField(default=0)),
                ("actual_shipped", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "original_file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "XLSX"),
                            ("zip", "ZIP"),
                            ("sql", "SQL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_file_path", models.TextField(blank=True, null=True)),
                ("converted_to_csv", models.BooleanField(default=False)),
                (
                    "conversion_status",
                    models.CharField(default="not_required", max_length=30),
                ),
                ("converted_file_count", models.IntegerField(default=0)),
                ("converted_csv_folder", models.TextField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(default="pending", max_length=30),
                ),
                ("import_status", models.CharField(default="pending", max_length=30)),
                ("user_message", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefectEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("defect_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("severity", models.CharField(default="minor", max_length=30)),
                ("notes", models.TextField(blank=True, null=True)),
                ("rework_required", models.BooleanField(default=False)),
                ("scrap_required", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.customerorder",
                    ),
                ),
                (
                    "defect_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplychain.defecttype",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.part",
                    ),
                ),
                (
                    "process_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.processstep",
                    ),
                ),
                (
                    "root_cause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.rootcausecode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CapaCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("capa_number", models.CharField(max_length=100, unique=True)),
                ("opened_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("problem_statement", models.TextField()),
                ("corrective_action", models.TextField(blank=True, null=True)),
                ("preventive_action", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=40)),
                ("effectiveness_verified", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defect_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.defectevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_date", models.DateField()),
                ("on_hand_qty", models.IntegerField(default=0)),
                ("allocated_qty", models.IntegerField(default=0)),
                ("incoming_qty", models.IntegerField(default=0)),
                ("safety_stock_qty", models.IntegerField(default=0)),
                ("reorder_point_qty", models.IntegerField(default=0)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.part",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DigitalChecklistResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("checklist_name", models.CharField(max_length=150)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.customerorder",
                    ),
                ),
                (
                    "process_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.processstep",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ControlChartSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("signal_date", models.DateField()),
                ("metric_name", models.CharField(max_length=120)),
                ("signal_type", models.CharField(max_length=120)),
                (
                    "observed_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "center_line",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "upper_control_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "lower_control_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("status", models.CharField(default="open", max_length=30)),
                (
                    "process_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.processstep",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("skin_tone", "Skin Tone"),
                            ("face_shape", "Face Shape"),
                            ("haircut", "Haircut"),
                            ("hair_color", "Hair Color"),
                            ("eye_color", "Eye Color"),
                            ("outfit", "Outfit"),
                            ("glasses", "Glasses"),
                        ],
                        max_length=50,
                    ),
                ),
                ("option_code", models.CharField(max_length=50)),
                ("option_name", models.CharField(max_length=120)),
            ],
            options={
                "unique_together": {("option_type", "option_code")},
            },
        ),
        migrations.CreateModel(
            name="QualityCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("cost_date", models.DateField()),
                (
                    "scrap_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rework_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "return_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "warranty_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expedite_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "defect_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.defectevent",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.customerorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("measurement_date", models.DateField()),
                ("metric_name", models.CharField(max_length=120)),
                (
                    "measured_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "lower_spec_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "upper_spec_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.part",
                    ),
                ),
                (
                    "process_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.processstep",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("return_date", models.DateField()),
                ("return_reason", models.CharField(max_length=150)),
                ("damaged_return", models.BooleanField(default=False)),
                ("wrong_assembly", models.BooleanField(default=False)),
                ("customer_dissatisfaction", models.BooleanField(default=False)),
                (
                    "refund_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "replacement_shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rework_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.customerorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_part_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "shipping_cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tariff_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "lead_time_days_mean",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "lead_time_days_std",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("minimum_order_quantity", models.PositiveIntegerField(default=1)),
                ("order_multiple", models.PositiveIntegerField(default=1)),
                ("capacity_per_month", models.PositiveIntegerField(default=0)),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(decimal_places=4, default=1, max_digits=6),
                ),
                (
                    "supplier_dpmo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.part",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.supplier",
                    ),
                ),
            ],
            options={
                "unique_together": {("part", "supplier")},
            },
        ),
        migrations.CreateModel(
            name="SupplierLotQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lot_number", models.CharField(max_length=120)),
                ("received_date", models.DateField()),
                ("units_received", models.IntegerField(default=0)),
                ("units_inspected", models.IntegerField(default=0)),
                ("defects_found", models.IntegerField(default=0)),
                ("accepted", models.BooleanField(default=True)),
                (
                    "supplier_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.supplierpart",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("recommendation_date", models.DateField()),
                ("forecast_qty", models.IntegerField(default=0)),
                ("available_qty", models.IntegerField(default=0)),
                ("safety_stock_qty", models.IntegerField(default=0)),
                ("recommended_order_qty", models.IntegerField(default=0)),
                ("recommended_order_date", models.DateField(blank=True, null=True)),
                ("risk_level", models.CharField(default="green", max_length=30)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplychain.part",
                    ),
                ),
                (
                    "supplier_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="supplychain.supplierpart",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
