# Generated by Django 5.2.13 on 2026-04-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyDollUnitSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "year_month",
                    models.CharField(db_index=True, max_length=7, unique=True),
                ),
                ("units_sold", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Monthly doll unit sale",
                "verbose_name_plural": "Monthly doll unit sales",
                "ordering": ["year_month"],
            },
        ),
    ]
