"""
Remove Part rows that are no longer in the unified OptiDoll catalog (SKU-OPT-*)
generated by supplychain.catalog_parts.build_catalog_rows().

By default only considers parts whose part_number starts with SKU-OPT-, so rows
from part_master.csv (e.g. HEAD_ST1_FACE1) are never touched.

Usage:
  python manage.py cleanup_catalog_parts              # dry-run (default)
  python manage.py cleanup_catalog_parts --execute    # delete orphans
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from supplychain import catalog_parts
from supplychain.models import Part


class Command(BaseCommand):
    help = (
        "Delete SKU-OPT-* Part rows not present in the current catalog_parts "
        "template (dry-run unless --execute)."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--execute",
            action="store_true",
            help="Actually delete orphan parts (default is dry-run only).",
        )
        parser.add_argument(
            "--prefix",
            default="SKU-OPT-",
            help="Only consider parts whose part_number starts with this prefix (default: SKU-OPT-).",
        )

    def handle(self, *args, **options):
        execute = options["execute"]
        prefix = options["prefix"] or ""

        canonical = {r["part_number"] for r in catalog_parts.build_catalog_rows()}
        qs = Part.objects.all()
        if prefix:
            qs = qs.filter(part_number__startswith=prefix)

        orphans = qs.exclude(part_number__in=canonical).order_by("part_number")
        count = orphans.count()

        if count == 0:
            self.stdout.write(self.style.SUCCESS("No orphan catalog parts to remove."))
            return

        self.stdout.write(
            f"Found {count} part(s) not in current catalog "
            f"({len(canonical)} canonical SKU-OPT rows)."
        )
        for p in orphans[:50]:
            self.stdout.write(f"  - {p.part_number} ({p.part_name})")
        if count > 50:
            self.stdout.write(f"  ... and {count - 50} more.")

        if not execute:
            self.stdout.write(
                self.style.WARNING(
                    "Dry-run only. Pass --execute to delete these parts. "
                    "Re-import or sync catalog rows afterward if you need the current SKUs in the database."
                )
            )
            return

        with transaction.atomic():
            deleted, _ = orphans.delete()
        self.stdout.write(
            self.style.SUCCESS(
                f"Deleted {deleted} row(s) (including CASCADE dependents where applicable)."
            )
        )
